import os

content = """- group: 从这里开始
  pages:
    - index
    - start/getting-started
    - start/wizard
    - start/setup
    - start/pairing
    - start/clawd
    - start/showcase
    - start/hubs
    - start/onboarding
    - start/lore
- group: 帮助
  pages:
    - help/index
    - help/troubleshooting
    - help/faq
- group: 安装与更新
  pages:
    - install/index
    - install/installer
    - install/updating
    - install/development-channels
    - install/uninstall
    - install/ansible
    - install/nix
    - install/docker
    - railway
    - render
    - install/bun
- group: 命令行 (CLI)
  pages:
    - cli/index
    - cli/setup
    - cli/onboard
    - cli/configure
    - cli/doctor
    - cli/dashboard
    - cli/reset
    - cli/uninstall
    - cli/browser
    - cli/message
    - cli/agent
    - cli/agents
    - cli/status
    - cli/health
    - cli/sessions
    - cli/channels
    - cli/directory
    - cli/skills
    - cli/plugins
    - cli/memory
    - cli/models
    - cli/logs
    - cli/system
    - cli/nodes
    - cli/approvals
    - cli/gateway
    - cli/tui
    - cli/voicecall
    - cli/cron
    - cli/dns
    - cli/docs
    - cli/hooks
    - cli/pairing
    - cli/security
    - cli/update
    - cli/sandbox
- group: 核心概念
  pages:
    - concepts/architecture
    - concepts/agent
    - concepts/agent-loop
    - concepts/system-prompt
    - concepts/context
    - token-use
    - concepts/oauth
    - concepts/agent-workspace
    - concepts/memory
    - concepts/multi-agent
    - concepts/compaction
    - concepts/session
    - concepts/session-pruning
    - concepts/sessions
    - concepts/session-tool
    - concepts/presence
    - concepts/channel-routing
    - concepts/messages
    - concepts/streaming
    - concepts/markdown-formatting
    - concepts/groups
    - concepts/group-messages
    - concepts/typing-indicators
    - concepts/queue
    - concepts/retry
    - concepts/model-providers
    - concepts/models
    - concepts/model-failover
    - concepts/usage-tracking
    - concepts/timezone
    - concepts/typebox
- group: 网关与运维
  pages:
    - gateway
    - gateway/protocol
    - gateway/bridge-protocol
    - gateway/pairing
    - gateway/gateway-lock
    - environment
    - gateway/configuration
    - gateway/multiple-gateways
    - gateway/configuration-examples
    - gateway/authentication
    - gateway/openai-http-api
    - gateway/tools-invoke-http-api
    - gateway/cli-backends
    - gateway/local-models
    - gateway/background-process
    - gateway/health
    - gateway/heartbeat
    - gateway/doctor
    - gateway/logging
    - gateway/security
    - gateway/sandbox-vs-tool-policy-vs-elevated
    - gateway/sandboxing
    - gateway/troubleshooting
    - debugging
    - gateway/remote
    - gateway/remote-gateway-readme
    - gateway/discovery
    - gateway/bonjour
    - gateway/tailscale
- group: 网页与界面
  pages:
    - web
    - web/control-ui
    - web/dashboard
    - web/webchat
    - tui
- group: 聊天渠道
  pages:
    - channels/index
    - channels/whatsapp
    - channels/telegram
    - channels/grammy
    - channels/discord
    - channels/slack
    - channels/googlechat
    - channels/feishu
    - channels/mattermost
    - channels/signal
    - channels/imessage
    - channels/msteams
    - channels/matrix
    - channels/zalo
    - channels/zalouser
    - broadcast-groups
    - channels/troubleshooting
    - channels/location
- group: 模型提供商
  pages:
    - providers/index
    - providers/models
    - providers/openai
    - providers/anthropic
    - bedrock
    - providers/moonshot
    - providers/minimax
    - providers/vercel-ai-gateway
    - providers/openrouter
    - providers/synthetic
    - providers/opencode
    - providers/glm
    - providers/zai
- group: 自动化与钩子
  pages:
    - hooks
    - hooks/soul-evil
    - automation/auth-monitoring
    - automation/webhook
    - automation/gmail-pubsub
    - automation/cron-jobs
    - automation/cron-vs-heartbeat
    - automation/poll
- group: 工具与技能
  pages:
    - tools
    - tools/lobster
    - tools/llm-task
    - plugin
    - plugins/voice-call
    - plugins/zalouser
    - tools/exec
    - tools/web
    - tools/apply-patch
    - tools/elevated
    - tools/browser
    - tools/browser-login
    - tools/chrome-extension
    - tools/browser-linux-troubleshooting
    - tools/slash-commands
    - tools/thinking
    - tools/agent-send
    - tools/subagents
    - multi-agent-sandbox-tools
    - tools/reactions
    - tools/skills
    - tools/skills-config
    - tools/clawdhub
- group: 节点与媒体
  pages:
    - nodes
    - nodes/camera
    - nodes/images
    - nodes/audio
    - nodes/location-command
    - nodes/voicewake
    - nodes/talk
- group: 平台支持
  pages:
    - platforms
    - platforms/macos
    - platforms/macos-vm
    - platforms/ios
    - platforms/android
    - platforms/windows
    - platforms/linux
    - platforms/fly
    - platforms/hetzner
    - platforms/gcp
    - platforms/exe-dev
- group: macOS 伴侣应用
  pages:
    - platforms/mac/dev-setup
    - platforms/mac/menu-bar
    - platforms/mac/voicewake
    - platforms/mac/voice-overlay
    - platforms/mac/webchat
    - platforms/mac/canvas
    - platforms/mac/child-process
    - platforms/mac/health
    - platforms/mac/icon
    - platforms/mac/logging
    - platforms/mac/permissions
    - platforms/mac/remote
    - platforms/mac/signing
    - platforms/mac/release
    - platforms/mac/bundled-gateway
    - platforms/mac/xpc
    - platforms/mac/skills
    - platforms/mac/peekaboo
- group: 参考与模板
  pages:
    - testing
    - scripts
    - reference/session-management-compaction
    - reference/rpc
    - reference/device-models
    - reference/test
    - reference/RELEASING
    - reference/AGENTS.default
    - reference/templates/AGENTS
    - reference/templates/BOOT
    - reference/templates/BOOTSTRAP
    - reference/templates/HEARTBEAT
    - reference/templates/IDENTITY
    - reference/templates/SOUL
    - reference/templates/TOOLS
    - reference/templates/USER"""

with open('_data/navigation.yml', 'w', encoding='utf-8') as f:
    f.write(content)
